name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: Amazon Linux

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get -y update
            sudo apt-get install -y apache2
            sudo systemctl start apache2
            sudo systemctl enable apache2
            cd home
            sudo mv * /var/www/html
Top comments (5)

Subscribe
pic
Add to the discussion
 I've read the code of conduct
 
 
darkmavis1980 profile image
Alessio Michelini
•
Jun 3 '23

Just one typo, you said deploy to "master" branch, and then show "main" in the example ;-)


2
 likes
Like
Reply
 
 
yeshwanthlm profile image
Yeshwanth 
•
Jun 23 '23

Corrected! Thanks Alessio Michelini :)


2
 likes
Like
Reply
 
 
jai_venkataarunakula_4d profile image
Jai Venkata Arun Akula
•
Jun 7

It is not working I guess everyone is getting below error

ssh: Could not resolve hostname linux_1709424878705: Temporary failure in name resolution

rsync: connection unexpectedly closed (0 bytes received so far) [sender]

rsync error: unexplained error (code 255) at io.c(231) [sender=3.2.7]

[Rsync] error:
Error: rsync exited with code 255
at ChildProcess. (//runner/work/_actions/easingthemes/ssh-deploy/main/dist/index.js:2:2603)
at ChildProcess.emit (node:events:514:28)
at ChildProcess._handle.onexit (node:internal/child_process:294:12) {
code: 255
}
[Rsync] stderr:
Warning: Identity file //runner/.ssh/deploy_key_Amazon not accessible: No such file or directory.
ssh: Could not resolve hostname linux_1709424878705: Temporary failure in name resolution
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(231) [sender=3.2.7]

[Rsync] stdout:

[Rsync] command:
================================================================
Error: R] rsync exited with code 255

Warning: Identity file /***/runner/.ssh/deploy_key_Amazon not accessible: No such file or directory.
ssh: Could not resolve hostname linux_1709424878705: Temporary failure in name resolution
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(231) [sender=3.2.7]

rsync //runner/work/Host-Resume-on-EC2/Host-Resume-on-EC2/ Amazon\ Linux@:* --rsh "ssh -p 22 -i //runner/.ssh/deploy_key__1709424878705 -o StrictHostKeyChecking=no" --recursive --exclude= -rlgoDzvc -i

please suggest I need to solution quickly


1
 like
Like
Reply
 
 
surinderpanwar05 profile image
surinder
•
Sep 18 '23

err: Synchronizing state of apache2.service with SysV service script with /lib/systemd/systemd-sysv-install.
err: Executing: /lib/systemd/systemd-sysv-install enable apache2
err: mv: cannot move 'css' to '/var/www/html/css': Directory not empty
err: mv: cannot move 'dashbord' to '/var/www/html/dashbord': Directory not empty
err: mv: cannot move 'js' to '/var/www/html/js': Directory not empty
err: mv: cannot move 'main' to '/var/www/html/main': Directory not empty
err: mv: cannot move 'rocket' to '/var/www/html/rocket': Directory not empty
err: mv: cannot move 'script' to '/var/www/html/script': Directory not empty

hi these error showing. First deploy work perfectly fine. but when i did changes in existing files then its not deploy on aws EC2 ubuntu 22. please give me solution. your help will be really appreciate.


Like
Reply
 
 
yudiztaukirkatava profile image
Yudiz_TaukirKatava
•
Jan 2

In your commands, just use '-r' option. like, "mv -r css /var/www/html/"


1
 like
Like
Reply
Code of Conduct • Report abuse
profile
Pieces.app
PROMOTED

A Workflow Copilot. Tailored to You.
Pieces.app image

Our desktop app, with its intelligent copilot, streamlines coding by generating snippets, extracting code from screenshots, and accelerating problem-solving.

Read the docs

Read next
saroj_khanal_e98ddbafdd66 profile image
KMP Libraries
saroj khanal - Jun 26

r4nd3l profile image
Dev: IoT
Matt Miller - Jun 25

ivansing profile image
Foundations of Logical Thinking in Programming
IvanDev - Jun 25

doctorserone profile image
Django AllAuth Chapter 1 - The All-in-one solution for Auth in Django
Andrés Álvarez Iglesias - Jun 26


Yeshwanth
Follow
AWS Cloud Engineer | AWS Community Builder
LOCATION
India
EDUCATION
B.E, Electronics and Communication
PRONOUNS
He/Him
WORK
Cloud Engineer
JOINED
Mar 3, 2023
More from Yeshwanth
Top 10 AWS Services You Should Know!
#aws #azure #gcp #cloud
Complete Roadmap to Learn and Master Kubernetes
#cloudnative #kubernetes #docker #containers
Developer Advocate 🥑
#aws #awscommunity #advocacy #cloud
DEV Community

Billboard image

Heads up! The Stellar Smart Contract Challenge is Launching Soon on July 10.
Follow Stellar Challenge so you don't miss the announcement.

Learn more here

name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt-get -y update
            sudo apt-get install -y apache2
            sudo systemctl start apache2
            sudo systemctl enable apache2
            cd home
            sudo mv * /var/www/html
